// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#ifndef __BINDINGS_TRUSTMARK_CONFIG_H
#define __BINDINGS_TRUSTMARK_CONFIG_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct trustmark_config_string_t {
  uint8_t*ptr;
  size_t len;
} trustmark_config_string_t;

// An error type that encapsulates the different errors that can occur fetching configuration values.
typedef struct wasi_config_store_error_t {
  uint8_t tag;
  union {
    trustmark_config_string_t     upstream;
    trustmark_config_string_t     io;
  } val;
} wasi_config_store_error_t;

// This indicates an error from an "upstream" config source.
// As this could be almost _anything_ (such as Vault, Kubernetes ConfigMaps, KeyValue buckets, etc),
// the error message is a string.
#define WASI_CONFIG_STORE_ERROR_UPSTREAM 0
// This indicates an error from an I/O operation.
// As this could be almost _anything_ (such as a file read, network connection, etc),
// the error message is a string.
// Depending on how this ends up being consumed,
// we may consider moving this to use the `wasi:io/error` type instead.
// For simplicity right now in supporting multiple implementations, it is being left as a string.
#define WASI_CONFIG_STORE_ERROR_IO 1

typedef struct {
  bool is_some;
  trustmark_config_string_t val;
} trustmark_config_option_string_t;

typedef struct {
  bool is_err;
  union {
    trustmark_config_option_string_t ok;
    wasi_config_store_error_t err;
  } val;
} wasi_config_store_result_option_string_error_t;

typedef struct {
  trustmark_config_string_t f0;
  trustmark_config_string_t f1;
} trustmark_config_tuple2_string_string_t;

typedef struct {
  trustmark_config_tuple2_string_string_t *ptr;
  size_t len;
} trustmark_config_list_tuple2_string_string_t;

typedef struct {
  bool is_err;
  union {
    trustmark_config_list_tuple2_string_string_t ok;
    wasi_config_store_error_t err;
  } val;
} wasi_config_store_result_list_tuple2_string_string_error_t;

// Imported Functions from `wasi:config/store@0.2.0-rc.1`
// Gets a configuration value of type `string` associated with the `key`.
// 
// The value is returned as an `option<string>`. If the key is not found,
// `Ok(none)` is returned. If an error occurs, an `Err(error)` is returned.
extern bool wasi_config_store_get(trustmark_config_string_t *key, trustmark_config_option_string_t *ret, wasi_config_store_error_t *err);
// Gets a list of configuration key-value pairs of type `string`.
// 
// If an error occurs, an `Err(error)` is returned.
extern bool wasi_config_store_get_all(trustmark_config_list_tuple2_string_string_t *ret, wasi_config_store_error_t *err);

// Helper Functions

void wasi_config_store_error_free(wasi_config_store_error_t *ptr);

void trustmark_config_option_string_free(trustmark_config_option_string_t *ptr);

void wasi_config_store_result_option_string_error_free(wasi_config_store_result_option_string_error_t *ptr);

void trustmark_config_tuple2_string_string_free(trustmark_config_tuple2_string_string_t *ptr);

void trustmark_config_list_tuple2_string_string_free(trustmark_config_list_tuple2_string_string_t *ptr);

void wasi_config_store_result_list_tuple2_string_string_error_free(wasi_config_store_result_list_tuple2_string_string_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void trustmark_config_string_set(trustmark_config_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void trustmark_config_string_dup(trustmark_config_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void trustmark_config_string_dup_n(trustmark_config_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void trustmark_config_string_free(trustmark_config_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
