// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
#include "trustmark_config.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `wasi:config/store@0.2.0-rc.1`

__attribute__((__import_module__("wasi:config/store@0.2.0-rc.1"), __import_name__("get")))
extern void __wasm_import_wasi_config_store_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("wasi:config/store@0.2.0-rc.1"), __import_name__("get-all")))
extern void __wasm_import_wasi_config_store_get_all(uint8_t *);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void wasi_config_store_error_free(wasi_config_store_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      trustmark_config_string_free(&ptr->val.upstream);
      break;
    }
    case 1: {
      trustmark_config_string_free(&ptr->val.io);
      break;
    }
  }
}

void trustmark_config_option_string_free(trustmark_config_option_string_t *ptr) {
  if (ptr->is_some) {
    trustmark_config_string_free(&ptr->val);
  }
}

void wasi_config_store_result_option_string_error_free(wasi_config_store_result_option_string_error_t *ptr) {
  if (!ptr->is_err) {
    trustmark_config_option_string_free(&ptr->val.ok);
  } else {
    wasi_config_store_error_free(&ptr->val.err);
  }
}

void trustmark_config_tuple2_string_string_free(trustmark_config_tuple2_string_string_t *ptr) {
  trustmark_config_string_free(&ptr->f0);
  trustmark_config_string_free(&ptr->f1);
}

void trustmark_config_list_tuple2_string_string_free(trustmark_config_list_tuple2_string_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    trustmark_config_tuple2_string_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      trustmark_config_tuple2_string_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void wasi_config_store_result_list_tuple2_string_string_error_free(wasi_config_store_result_list_tuple2_string_string_error_t *ptr) {
  if (!ptr->is_err) {
    trustmark_config_list_tuple2_string_string_free(&ptr->val.ok);
  } else {
    wasi_config_store_error_free(&ptr->val.err);
  }
}

void trustmark_config_string_set(trustmark_config_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void trustmark_config_string_dup(trustmark_config_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void trustmark_config_string_dup_n(trustmark_config_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void trustmark_config_string_free(trustmark_config_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool wasi_config_store_get(trustmark_config_string_t *key, trustmark_config_option_string_t *ret, wasi_config_store_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_config_store_get((uint8_t *) (*key).ptr, (*key).len, ptr);
  wasi_config_store_result_option_string_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      trustmark_config_option_string_t option;
      switch ((int32_t) *((uint8_t*) (ptr + sizeof(void*)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (trustmark_config_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_config_store_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.upstream = (trustmark_config_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.io = (trustmark_config_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool wasi_config_store_get_all(trustmark_config_list_tuple2_string_string_t *ret, wasi_config_store_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_wasi_config_store_get_all(ptr);
  wasi_config_store_result_list_tuple2_string_string_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (trustmark_config_list_tuple2_string_string_t) { (trustmark_config_tuple2_string_string_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      wasi_config_store_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.upstream = (trustmark_config_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          variant.val.io = (trustmark_config_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_trustmark_config(void);
__attribute__((used))
void __component_type_object_force_link_trustmark_config_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_trustmark_config();
}
